### ISSUE TITLE
gui-progressbar and gui-circle-loader components lack progress visualization

### ISSUE THREAD

**Issue by mattrei** [rdub80/aframe-gui#1]
Hi,

i absolutely love this project. Its amazing that you implemented so much GUI components here. 

However the `gui-circle-loader` and `gui-progressbar` are not complete because I can't visualize a  progress here. Also the code does not implement it or is commented out. Are there specific reasons for this? The implementation is straight forward or are you unsure about the API?

THX for clarification.

**Comment by rdub80** [comment]
Hi Matthias, thanks for reaching out!
We have a working example of the progress bar component [here](https://aframe-gui.herokuapp.com/demo.html)
I am adding @lmalave on this thread since he built this demo.

Please have a look at our other [examples and case-studies](https://rdub80.github.io/aframe-gui/examples/index.html) in the meantime

**Comment by mattrei** [comment]
thx for pointing this out.

However I think it would be much nicer to implement a _progress_ property in the `gui-progressbar` schema. The current solution relies on getting the  "progress_meter" DOM entity. I think this is a bit cumbersome to work wit.

What do you think?

**Comment by lmalave** [comment]
Great suggestion  - we will make that change!
